Interface created for extension settings
BalticAmadeus/ProBro pull request #256
Opened 2023-02-21 10:32 UTC by MatasLaz

2023-02-23 21:12 UTC, PauliusKu commented
Index and field tabs doesn't work

![image](https://user-images.githubusercontent.com/36190136/221031211-569a64db-2a0d-4abe-91e2-5010f5d0f52b.png)

2023-02-23 21:16 UTC, PauliusKu requested changes
Index and field tabs doesn't work:
![image](https://user-images.githubusercontent.com/36190136/221032067-f726dbed-d102-464a-bbaa-6b54971bed7c.png)

2023-02-24 09:17 UTC, Knijus commented on src/common/IExtensionSettings.ts
> +    openEdge: string}
Put curly brace into next line.
Try be consistent with code formatting . Use "format document" for newly created files and "format selection" for your part of code.

2023-02-24 13:31 UTC, Knijus approved these changes

2023-02-27 08:02 UTC, PauliusKu approved these changes

2023-02-27 08:02 UTC, merged